version: '3.8'

services:
  app:
    build: .
    volumes:
      - ${PWD}/.env:/app/.env:ro
      - ${PWD}/ctf_bot.db:/app/ctf_bot.db
      - ${PWD}/logs:/app/logs
      - ${PWD}/assignments.json:/app/assignments.json
      - ${PWD}/challenge_assignments.json:/app/challenge_assignments.json
    environment:
      - PYTHONUNBUFFERED=1
